/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  
  about: [
    {type: 'autogenerated', dirName: 'about'},
    {
      type: 'category',
      label: 'Protocol Specs',
      collapsed: true,
      link: {type: 'doc', id: 'specs/README'},
      items: [
          {
            type: 'category',
            label: 'Beacon Chain',
            collapsed: true,
            link: {type: 'doc', id: 'specs/gbc/README'},
            items: [
              'specs/gbc/upgradeability',
              'specs/gbc/faq',
            ],
          },
          {
            type: 'category',
            label: 'Consensus',
            collapsed: true,
            link: {type: 'doc', id: 'specs/consensus/README'},
            items: [
              'specs/consensus/aura',
              'specs/consensus/posdao',
              'specs/consensus/gbc',
            ],
          },
          {
            type: 'category',
            label: 'Hard Forks',
            collapsed: true,
            link: {type: 'doc', id: 'specs/hard-forks/README'},
            items: [
              'specs/hard-forks/21735000',
              'specs/hard-forks/19040000',
              'specs/hard-forks/16101500',
              'specs/hard-forks/9186425',
              'specs/hard-forks/7298030',
              'specs/hard-forks/2508800',
              'specs/hard-forks/1604400',
              'specs/hard-forks/spec.json-update',
            ],
          },
          'specs/security-audit',
          'specs/media-kit',
          'specs/community',

      ],
    },
  ],
  userguide: [{type: 'autogenerated', dirName: 'user-guide'}],
  developers: [{type: 'autogenerated', dirName: 'developers'}],
  node: [
    'node/README',
    'node/incentives',
    {
      type: 'category',
      label: 'Validator Guide',
      collapsed: false,
      link: {type: 'doc', id: 'node/get-started/README'},
      items: [
        "node/run-consensus-layer-node/consensus-layer-validator",
        "node/run-execution-layer-node/execution-layer-validator",
        "node/validator-deposits/validator-deposits",
        "node/validator-withdrawls/validator-withdrawls",
        "node/migrating-a-validator/migrating-a-validator",
        "node/monitoring-your-nodes/monitoring-nodes",
        "node/voluntary-exit/voluntary-exit",
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Client setup',
    //   collapsed: true,
    //   link: {type: 'doc', id: 'node/client/README'},
    //   items: [
    //     "node/client/lighthouse",
    //     "node/client/nimbus",
    //     "node/client/prysm",
    //     "node/client/nethermind-node-setup",
    //     "node/client/connect-to-a-gc-node",
    //     "node/client/node-monitoring",
    //     "node/client/migrate-clients",
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Operations',
    //   collapsed: true,
    //   //link: {type: 'doc', id: 'node/operations/README'},
    //   items: [
    //     "node/operations/README",
    //     "node/operations/deposit-safety-instructions",
    //     "node/operations/manual-deposit-method",
    //     "node/operations/convert-gno-to-mgno",
    //     "node/operations/validator-withdrawals",
    //     "node/operations/voluntary-exit",
    //     "node/operations/migrating-a-validator",
    //   ],
    // },
    {
      type: 'category',
      label: 'Tools',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'Explorer',
          href: 'https://beacon.gnosischain.com/',
        },
        'node/tools/beacon-chain-analytics',
        {
          type: 'link',
          label: 'Deposit Tool',
          href: 'https://deposit.gnosischain.com/',
        },
        'node/tools/liquid-staking',
      ],
    },
    {
      type: 'link',
      label: 'Landing Page',
      href: 'https://www.gnosischain.com/',
    },
  ],
  bridge: [{type: 'autogenerated', dirName: 'bridges'}],
  tools: [{type: 'autogenerated', dirName: 'tools'}],
  integrations: [{type: 'autogenerated', dirName: 'integrations'}],
  ecosystems: [{type: 'autogenerated', dirName: 'ecosystems'}],
  
/*
  overview: [
    {type: 'autogenerated', dirName: 'tutorials'},
    {type: 'autogenerated', dirName: '.'}
  ],
  governance: [
    'governance/README',
    'governance/community',
    {
      type: 'category',
      label: 'Gnosis Chain Bridge',
      collapsed: false,
      items: [
        'governance/bridge',
        'governance/board-decisions',
      ],
    },
  ],
  */
};

module.exports = sidebars;
